In [1]:
import numpy as np
from pyaabb import pyaabb
import k3d

In [2]:
def create_boxes(point_lst):
    min_corners = []
    max_corners = []

    for p in point_lst:
        min_tmp = []
        max_tmp = []
        for i in range(3):
            min_tmp.append(min(p[0][i], p[1][i]))
            max_tmp.append(max(p[0][i], p[1][i]))
        min_corners.append(min_tmp)
        max_corners.append(max_tmp)

    corners = np.concatenate((np.array(min_corners)[:, None], np.array(max_corners)[:, None]), axis=1)
    return corners


In [3]:
def generate_dots(theta, z):
    r = z**2 + 1
    x = r * np.sin(theta)
    y = r * np.cos(theta)
    return x, y

# 1

In [5]:
theta = np.linspace(0, 1, 10, dtype=np.float32)
z = np.linspace(-5, 1, 10, dtype=np.float32)
x, y = generate_dots(theta, z)

tmp_1 = np.concatenate((x[0:-1, None], y[0:-1, None], z[0:-1, None]), axis=-1)
tmp_2 = np.concatenate((x[1:, None], y[1:, None], z[1:, None]), axis=-1)
point_lines = np.concatenate((tmp_1[:, None], tmp_2[:, None]), axis=1)

In [7]:
corners = create_boxes(point_lines)
method = pyaabb.AABB()
method.build(corners)

In [9]:
i = np.random.randint(0, len(point_lines))
points = np.array([[0, 0, 0], 
                   [0.5,  2, -1], 
                   [1, 1, -0.5], 
                   [0.5, 0.5, 0.5], 
                   point_lines[i][0], 
                   point_lines[i][1]]).astype(float)

for p in points:
        print(p, 'segment id {}'.format(method.point_find_bbox(p)))

[0. 0. 0.] segment id []
[ 0.5  2.  -1. ] segment id []
[ 1.   1.  -0.5] segment id [6]
[0.5 0.5 0.5] segment id []
[ 3.27194715  9.4495697  -3.        ] segment id [2, 3]
[ 2.77082992  5.81836414 -2.33333325] segment id [3, 4]


In [4]:
def illustrate(point_lines, points):
    plot = k3d.plot()

    line = k3d.line(point_lines, width=0.2)
    plot += line
    for p in points:
        c = [0xff0000]
        id_ = method.point_find_bbox(p)
        if len(id_) > 0:
            point = k3d.points(p, colors=c, point_size=0.3)
            for i in id_:
                line = k3d.line(point_lines[i], colors=[c, c], width=0.2)
                plot += line
        else:
            point = k3d.points(p, colors=0xf0001, point_size=0.3)
        plot += point

    plot.display()


In [11]:
illustrate(point_lines, points)

Output()

# 2

In [5]:
theta = np.linspace(0, 1, 10, dtype=np.float32)
z = np.linspace(-1, 1, 10, dtype=np.float32)
x, y = generate_dots(theta, z)

tmp_1 = np.concatenate((x[0:-1, None], y[0:-1, None], z[0:-1, None]), axis=-1)
tmp_2 = np.concatenate((x[1:, None], y[1:, None], z[1:, None]), axis=-1)
point_lines = np.concatenate((tmp_1[:, None], tmp_2[:, None]), axis=1)

In [6]:
corners = create_boxes(point_lines)
method = pyaabb.AABB()
method.build(corners)

In [9]:
i = np.random.randint(0, len(point_lines))
points = np.array([[0, 0, 0], 
                   [0.5,  2, -1], 
                   [1, 1, -0.5], 
                   [0.5, 0.5, 0.5], 
                   [1000, 1000, 1000],
                   point_lines[i][0], 
                   point_lines[i][1]]).astype(float)

for p in points:
        print(p, 'segment id {}'.format(method.point_find_bbox(p)))

[0. 0. 0.] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[ 0.5  2.  -1. ] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[ 1.   1.  -0.5] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[0.5 0.5 0.5] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[1000. 1000. 1000.] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[0.53392667 0.86009651 0.11111111] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]
[0.68707758 0.87320811 0.33333334] segment id [0, 1, 2, 3, 4, 5, 6, 7, 8]


In [10]:
illustrate(point_lines, points)

Output()

# 3

In [23]:
theta = np.linspace(0, 1, 10, dtype=np.float32)
z = np.linspace(-3, 3, 10, dtype=np.float32)
x, y = generate_dots(theta, z)

tmp_1 = np.concatenate((x[0:-1, None], y[0:-1, None], z[0:-1, None]), axis=-1)
tmp_2 = np.concatenate((x[1:, None], y[1:, None], z[1:, None]), axis=-1)
point_lines = np.concatenate((tmp_1[:, None], tmp_2[:, None]), axis=1)

In [24]:
corners = create_boxes(point_lines)
method = pyaabb.AABB()
method.build(corners)

In [25]:
i = np.random.randint(0, len(point_lines))
points = np.array([[0, 0, 0], 
                   [2,  3, -1], 
                   [1, 1, -0.5], 
                   [0.5, 0.5, 0.5], 
                   point_lines[i][0], 
                   point_lines[i][1]]).astype(float)

for p in points:
        print(p, 'segment id {}'.format(method.point_find_bbox(p)))

[0. 0. 0.] segment id []
[ 2.  3. -1.] segment id []
[ 1.   1.  -0.5] segment id []
[0.5 0.5 0.5] segment id []
[ 0.65438944  1.88991392 -1.        ] segment id [2, 3]
[ 0.47772932  1.00316632 -0.33333334] segment id [3, 4]


In [26]:
illustrate(point_lines, points)

Output()